package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddAccountNoContentCode is the HTTP code returned for type AddAccountNoContent
const AddAccountNoContentCode int = 204

/*AddAccountNoContent successful operation

swagger:response addAccountNoContent
*/
type AddAccountNoContent struct {
}

// NewAddAccountNoContent creates AddAccountNoContent with default headers values
func NewAddAccountNoContent() *AddAccountNoContent {
	return &AddAccountNoContent{}
}

// WriteResponse to the client
func (o *AddAccountNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// AddAccountMethodNotAllowedCode is the HTTP code returned for type AddAccountMethodNotAllowed
const AddAccountMethodNotAllowedCode int = 405

/*AddAccountMethodNotAllowed Invalid input

swagger:response addAccountMethodNotAllowed
*/
type AddAccountMethodNotAllowed struct {
}

// NewAddAccountMethodNotAllowed creates AddAccountMethodNotAllowed with default headers values
func NewAddAccountMethodNotAllowed() *AddAccountMethodNotAllowed {
	return &AddAccountMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddAccountMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
