package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAccountNoContentCode is the HTTP code returned for type DeleteAccountNoContent
const DeleteAccountNoContentCode int = 204

/*DeleteAccountNoContent successful operation

swagger:response deleteAccountNoContent
*/
type DeleteAccountNoContent struct {
}

// NewDeleteAccountNoContent creates DeleteAccountNoContent with default headers values
func NewDeleteAccountNoContent() *DeleteAccountNoContent {
	return &DeleteAccountNoContent{}
}

// WriteResponse to the client
func (o *DeleteAccountNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// DeleteAccountBadRequestCode is the HTTP code returned for type DeleteAccountBadRequest
const DeleteAccountBadRequestCode int = 400

/*DeleteAccountBadRequest Invalid ID supplied

swagger:response deleteAccountBadRequest
*/
type DeleteAccountBadRequest struct {
}

// NewDeleteAccountBadRequest creates DeleteAccountBadRequest with default headers values
func NewDeleteAccountBadRequest() *DeleteAccountBadRequest {
	return &DeleteAccountBadRequest{}
}

// WriteResponse to the client
func (o *DeleteAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DeleteAccountNotFoundCode is the HTTP code returned for type DeleteAccountNotFound
const DeleteAccountNotFoundCode int = 404

/*DeleteAccountNotFound Account not found

swagger:response deleteAccountNotFound
*/
type DeleteAccountNotFound struct {
}

// NewDeleteAccountNotFound creates DeleteAccountNotFound with default headers values
func NewDeleteAccountNotFound() *DeleteAccountNotFound {
	return &DeleteAccountNotFound{}
}

// WriteResponse to the client
func (o *DeleteAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
