package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/onokonem/go-testrest/proto/models"
)

// DepositToAccountOKCode is the HTTP code returned for type DepositToAccountOK
const DepositToAccountOKCode int = 200

/*DepositToAccountOK successful operation

swagger:response depositToAccountOK
*/
type DepositToAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.Account `json:"body,omitempty"`
}

// NewDepositToAccountOK creates DepositToAccountOK with default headers values
func NewDepositToAccountOK() *DepositToAccountOK {
	return &DepositToAccountOK{}
}

// WithPayload adds the payload to the deposit to account o k response
func (o *DepositToAccountOK) WithPayload(payload *models.Account) *DepositToAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deposit to account o k response
func (o *DepositToAccountOK) SetPayload(payload *models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DepositToAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DepositToAccountBadRequestCode is the HTTP code returned for type DepositToAccountBadRequest
const DepositToAccountBadRequestCode int = 400

/*DepositToAccountBadRequest Invalid ID supplied

swagger:response depositToAccountBadRequest
*/
type DepositToAccountBadRequest struct {
}

// NewDepositToAccountBadRequest creates DepositToAccountBadRequest with default headers values
func NewDepositToAccountBadRequest() *DepositToAccountBadRequest {
	return &DepositToAccountBadRequest{}
}

// WriteResponse to the client
func (o *DepositToAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DepositToAccountNotFoundCode is the HTTP code returned for type DepositToAccountNotFound
const DepositToAccountNotFoundCode int = 404

/*DepositToAccountNotFound Account not found

swagger:response depositToAccountNotFound
*/
type DepositToAccountNotFound struct {
}

// NewDepositToAccountNotFound creates DepositToAccountNotFound with default headers values
func NewDepositToAccountNotFound() *DepositToAccountNotFound {
	return &DepositToAccountNotFound{}
}

// WriteResponse to the client
func (o *DepositToAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DepositToAccountInternalServerErrorCode is the HTTP code returned for type DepositToAccountInternalServerError
const DepositToAccountInternalServerErrorCode int = 500

/*DepositToAccountInternalServerError Operation error

swagger:response depositToAccountInternalServerError
*/
type DepositToAccountInternalServerError struct {
}

// NewDepositToAccountInternalServerError creates DepositToAccountInternalServerError with default headers values
func NewDepositToAccountInternalServerError() *DepositToAccountInternalServerError {
	return &DepositToAccountInternalServerError{}
}

// WriteResponse to the client
func (o *DepositToAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
