package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DepositToAccountNoContentCode is the HTTP code returned for type DepositToAccountNoContent
const DepositToAccountNoContentCode int = 204

/*DepositToAccountNoContent successful operation

swagger:response depositToAccountNoContent
*/
type DepositToAccountNoContent struct {
}

// NewDepositToAccountNoContent creates DepositToAccountNoContent with default headers values
func NewDepositToAccountNoContent() *DepositToAccountNoContent {
	return &DepositToAccountNoContent{}
}

// WriteResponse to the client
func (o *DepositToAccountNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// DepositToAccountBadRequestCode is the HTTP code returned for type DepositToAccountBadRequest
const DepositToAccountBadRequestCode int = 400

/*DepositToAccountBadRequest Invalid ID supplied

swagger:response depositToAccountBadRequest
*/
type DepositToAccountBadRequest struct {
}

// NewDepositToAccountBadRequest creates DepositToAccountBadRequest with default headers values
func NewDepositToAccountBadRequest() *DepositToAccountBadRequest {
	return &DepositToAccountBadRequest{}
}

// WriteResponse to the client
func (o *DepositToAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DepositToAccountNotFoundCode is the HTTP code returned for type DepositToAccountNotFound
const DepositToAccountNotFoundCode int = 404

/*DepositToAccountNotFound Account not found

swagger:response depositToAccountNotFound
*/
type DepositToAccountNotFound struct {
}

// NewDepositToAccountNotFound creates DepositToAccountNotFound with default headers values
func NewDepositToAccountNotFound() *DepositToAccountNotFound {
	return &DepositToAccountNotFound{}
}

// WriteResponse to the client
func (o *DepositToAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DepositToAccountInternalServerErrorCode is the HTTP code returned for type DepositToAccountInternalServerError
const DepositToAccountInternalServerErrorCode int = 500

/*DepositToAccountInternalServerError Operation error

swagger:response depositToAccountInternalServerError
*/
type DepositToAccountInternalServerError struct {
}

// NewDepositToAccountInternalServerError creates DepositToAccountInternalServerError with default headers values
func NewDepositToAccountInternalServerError() *DepositToAccountInternalServerError {
	return &DepositToAccountInternalServerError{}
}

// WriteResponse to the client
func (o *DepositToAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
