package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/onokonem/go-testrest/proto/models"
)

// ListAccountsOKCode is the HTTP code returned for type ListAccountsOK
const ListAccountsOKCode int = 200

/*ListAccountsOK successful operation

swagger:response listAccountsOK
*/
type ListAccountsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Account `json:"body,omitempty"`
}

// NewListAccountsOK creates ListAccountsOK with default headers values
func NewListAccountsOK() *ListAccountsOK {
	return &ListAccountsOK{}
}

// WithPayload adds the payload to the list accounts o k response
func (o *ListAccountsOK) WithPayload(payload []*models.Account) *ListAccountsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list accounts o k response
func (o *ListAccountsOK) SetPayload(payload []*models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAccountsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Account, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ListAccountsBadRequestCode is the HTTP code returned for type ListAccountsBadRequest
const ListAccountsBadRequestCode int = 400

/*ListAccountsBadRequest Invalid status value

swagger:response listAccountsBadRequest
*/
type ListAccountsBadRequest struct {
}

// NewListAccountsBadRequest creates ListAccountsBadRequest with default headers values
func NewListAccountsBadRequest() *ListAccountsBadRequest {
	return &ListAccountsBadRequest{}
}

// WriteResponse to the client
func (o *ListAccountsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
