package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/onokonem/go-testrest/proto/models"
)

// TransferBetweenAccountsOKCode is the HTTP code returned for type TransferBetweenAccountsOK
const TransferBetweenAccountsOKCode int = 200

/*TransferBetweenAccountsOK successful operation

swagger:response transferBetweenAccountsOK
*/
type TransferBetweenAccountsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Account `json:"body,omitempty"`
}

// NewTransferBetweenAccountsOK creates TransferBetweenAccountsOK with default headers values
func NewTransferBetweenAccountsOK() *TransferBetweenAccountsOK {
	return &TransferBetweenAccountsOK{}
}

// WithPayload adds the payload to the transfer between accounts o k response
func (o *TransferBetweenAccountsOK) WithPayload(payload []*models.Account) *TransferBetweenAccountsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the transfer between accounts o k response
func (o *TransferBetweenAccountsOK) SetPayload(payload []*models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TransferBetweenAccountsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Account, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// TransferBetweenAccountsBadRequestCode is the HTTP code returned for type TransferBetweenAccountsBadRequest
const TransferBetweenAccountsBadRequestCode int = 400

/*TransferBetweenAccountsBadRequest Invalid ID supplied

swagger:response transferBetweenAccountsBadRequest
*/
type TransferBetweenAccountsBadRequest struct {
}

// NewTransferBetweenAccountsBadRequest creates TransferBetweenAccountsBadRequest with default headers values
func NewTransferBetweenAccountsBadRequest() *TransferBetweenAccountsBadRequest {
	return &TransferBetweenAccountsBadRequest{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// TransferBetweenAccountsNotFoundCode is the HTTP code returned for type TransferBetweenAccountsNotFound
const TransferBetweenAccountsNotFoundCode int = 404

/*TransferBetweenAccountsNotFound Account not found

swagger:response transferBetweenAccountsNotFound
*/
type TransferBetweenAccountsNotFound struct {
}

// NewTransferBetweenAccountsNotFound creates TransferBetweenAccountsNotFound with default headers values
func NewTransferBetweenAccountsNotFound() *TransferBetweenAccountsNotFound {
	return &TransferBetweenAccountsNotFound{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// TransferBetweenAccountsInternalServerErrorCode is the HTTP code returned for type TransferBetweenAccountsInternalServerError
const TransferBetweenAccountsInternalServerErrorCode int = 500

/*TransferBetweenAccountsInternalServerError Operation error

swagger:response transferBetweenAccountsInternalServerError
*/
type TransferBetweenAccountsInternalServerError struct {
}

// NewTransferBetweenAccountsInternalServerError creates TransferBetweenAccountsInternalServerError with default headers values
func NewTransferBetweenAccountsInternalServerError() *TransferBetweenAccountsInternalServerError {
	return &TransferBetweenAccountsInternalServerError{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
