package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TransferBetweenAccountsNoContentCode is the HTTP code returned for type TransferBetweenAccountsNoContent
const TransferBetweenAccountsNoContentCode int = 204

/*TransferBetweenAccountsNoContent successful operation

swagger:response transferBetweenAccountsNoContent
*/
type TransferBetweenAccountsNoContent struct {
}

// NewTransferBetweenAccountsNoContent creates TransferBetweenAccountsNoContent with default headers values
func NewTransferBetweenAccountsNoContent() *TransferBetweenAccountsNoContent {
	return &TransferBetweenAccountsNoContent{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// TransferBetweenAccountsBadRequestCode is the HTTP code returned for type TransferBetweenAccountsBadRequest
const TransferBetweenAccountsBadRequestCode int = 400

/*TransferBetweenAccountsBadRequest Invalid ID supplied

swagger:response transferBetweenAccountsBadRequest
*/
type TransferBetweenAccountsBadRequest struct {
}

// NewTransferBetweenAccountsBadRequest creates TransferBetweenAccountsBadRequest with default headers values
func NewTransferBetweenAccountsBadRequest() *TransferBetweenAccountsBadRequest {
	return &TransferBetweenAccountsBadRequest{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// TransferBetweenAccountsNotFoundCode is the HTTP code returned for type TransferBetweenAccountsNotFound
const TransferBetweenAccountsNotFoundCode int = 404

/*TransferBetweenAccountsNotFound Account not found

swagger:response transferBetweenAccountsNotFound
*/
type TransferBetweenAccountsNotFound struct {
}

// NewTransferBetweenAccountsNotFound creates TransferBetweenAccountsNotFound with default headers values
func NewTransferBetweenAccountsNotFound() *TransferBetweenAccountsNotFound {
	return &TransferBetweenAccountsNotFound{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// TransferBetweenAccountsInternalServerErrorCode is the HTTP code returned for type TransferBetweenAccountsInternalServerError
const TransferBetweenAccountsInternalServerErrorCode int = 500

/*TransferBetweenAccountsInternalServerError Operation error

swagger:response transferBetweenAccountsInternalServerError
*/
type TransferBetweenAccountsInternalServerError struct {
}

// NewTransferBetweenAccountsInternalServerError creates TransferBetweenAccountsInternalServerError with default headers values
func NewTransferBetweenAccountsInternalServerError() *TransferBetweenAccountsInternalServerError {
	return &TransferBetweenAccountsInternalServerError{}
}

// WriteResponse to the client
func (o *TransferBetweenAccountsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
