package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/onokonem/go-testrest/proto/models"
)

// WithdrawAccountOKCode is the HTTP code returned for type WithdrawAccountOK
const WithdrawAccountOKCode int = 200

/*WithdrawAccountOK successful operation

swagger:response withdrawAccountOK
*/
type WithdrawAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.Account `json:"body,omitempty"`
}

// NewWithdrawAccountOK creates WithdrawAccountOK with default headers values
func NewWithdrawAccountOK() *WithdrawAccountOK {
	return &WithdrawAccountOK{}
}

// WithPayload adds the payload to the withdraw account o k response
func (o *WithdrawAccountOK) WithPayload(payload *models.Account) *WithdrawAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the withdraw account o k response
func (o *WithdrawAccountOK) SetPayload(payload *models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WithdrawAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WithdrawAccountBadRequestCode is the HTTP code returned for type WithdrawAccountBadRequest
const WithdrawAccountBadRequestCode int = 400

/*WithdrawAccountBadRequest Invalid ID supplied

swagger:response withdrawAccountBadRequest
*/
type WithdrawAccountBadRequest struct {
}

// NewWithdrawAccountBadRequest creates WithdrawAccountBadRequest with default headers values
func NewWithdrawAccountBadRequest() *WithdrawAccountBadRequest {
	return &WithdrawAccountBadRequest{}
}

// WriteResponse to the client
func (o *WithdrawAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// WithdrawAccountNotFoundCode is the HTTP code returned for type WithdrawAccountNotFound
const WithdrawAccountNotFoundCode int = 404

/*WithdrawAccountNotFound Account not found

swagger:response withdrawAccountNotFound
*/
type WithdrawAccountNotFound struct {
}

// NewWithdrawAccountNotFound creates WithdrawAccountNotFound with default headers values
func NewWithdrawAccountNotFound() *WithdrawAccountNotFound {
	return &WithdrawAccountNotFound{}
}

// WriteResponse to the client
func (o *WithdrawAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// WithdrawAccountInternalServerErrorCode is the HTTP code returned for type WithdrawAccountInternalServerError
const WithdrawAccountInternalServerErrorCode int = 500

/*WithdrawAccountInternalServerError Operation error

swagger:response withdrawAccountInternalServerError
*/
type WithdrawAccountInternalServerError struct {
}

// NewWithdrawAccountInternalServerError creates WithdrawAccountInternalServerError with default headers values
func NewWithdrawAccountInternalServerError() *WithdrawAccountInternalServerError {
	return &WithdrawAccountInternalServerError{}
}

// WriteResponse to the client
func (o *WithdrawAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
