package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWithdrawAccountParams creates a new WithdrawAccountParams object
// with the default values initialized.
func NewWithdrawAccountParams() WithdrawAccountParams {
	var ()
	return WithdrawAccountParams{}
}

// WithdrawAccountParams contains all the bound params for the withdraw account operation
// typically these are obtained from a http.Request
//
// swagger:parameters withdrawAccount
type WithdrawAccountParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Amount to be withdrawed
	  Required: true
	  In: query
	*/
	Amount int64
	/*Account id to update
	  Required: true
	  In: path
	*/
	ID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *WithdrawAccountParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAmount, qhkAmount, _ := qs.GetOK("amount")
	if err := o.bindAmount(qAmount, qhkAmount, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WithdrawAccountParams) bindAmount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("amount", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("amount", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("amount", "query", "int64", raw)
	}
	o.Amount = value

	return nil
}

func (o *WithdrawAccountParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}
