package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/onokonem/go-testrest/proto/restapi/operations/account"
)

// NewTestrestAPI creates a new Testrest instance
func NewTestrestAPI(spec *loads.Document) *TestrestAPI {
	return &TestrestAPI{
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
		spec:            spec,
		ServeError:      errors.ServeError,
		JSONConsumer:    runtime.JSONConsumer(),
		JSONProducer:    runtime.JSONProducer(),
		AccountAddAccountHandler: account.AddAccountHandlerFunc(func(params account.AddAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountAddAccount has not yet been implemented")
		}),
		AccountDeleteAccountHandler: account.DeleteAccountHandlerFunc(func(params account.DeleteAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountDeleteAccount has not yet been implemented")
		}),
		AccountDepositToAccountHandler: account.DepositToAccountHandlerFunc(func(params account.DepositToAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountDepositToAccount has not yet been implemented")
		}),
		AccountFindAccountByNameHandler: account.FindAccountByNameHandlerFunc(func(params account.FindAccountByNameParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountFindAccountByName has not yet been implemented")
		}),
		AccountGetAccountByIDHandler: account.GetAccountByIDHandlerFunc(func(params account.GetAccountByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountGetAccountByID has not yet been implemented")
		}),
		AccountListAccountsHandler: account.ListAccountsHandlerFunc(func(params account.ListAccountsParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountListAccounts has not yet been implemented")
		}),
		AccountTransferBetweenAccountsHandler: account.TransferBetweenAccountsHandlerFunc(func(params account.TransferBetweenAccountsParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountTransferBetweenAccounts has not yet been implemented")
		}),
		AccountWithdrawAccountHandler: account.WithdrawAccountHandlerFunc(func(params account.WithdrawAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation AccountWithdrawAccount has not yet been implemented")
		}),
	}
}

/*TestrestAPI This is a simple test rest service implementing very basic accounts manаgement system */
type TestrestAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// AccountAddAccountHandler sets the operation handler for the add account operation
	AccountAddAccountHandler account.AddAccountHandler
	// AccountDeleteAccountHandler sets the operation handler for the delete account operation
	AccountDeleteAccountHandler account.DeleteAccountHandler
	// AccountDepositToAccountHandler sets the operation handler for the deposit to account operation
	AccountDepositToAccountHandler account.DepositToAccountHandler
	// AccountFindAccountByNameHandler sets the operation handler for the find account by name operation
	AccountFindAccountByNameHandler account.FindAccountByNameHandler
	// AccountGetAccountByIDHandler sets the operation handler for the get account by ID operation
	AccountGetAccountByIDHandler account.GetAccountByIDHandler
	// AccountListAccountsHandler sets the operation handler for the list accounts operation
	AccountListAccountsHandler account.ListAccountsHandler
	// AccountTransferBetweenAccountsHandler sets the operation handler for the transfer between accounts operation
	AccountTransferBetweenAccountsHandler account.TransferBetweenAccountsHandler
	// AccountWithdrawAccountHandler sets the operation handler for the withdraw account operation
	AccountWithdrawAccountHandler account.WithdrawAccountHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *TestrestAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TestrestAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TestrestAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TestrestAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TestrestAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TestrestAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TestrestAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TestrestAPI
func (o *TestrestAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.AccountAddAccountHandler == nil {
		unregistered = append(unregistered, "account.AddAccountHandler")
	}

	if o.AccountDeleteAccountHandler == nil {
		unregistered = append(unregistered, "account.DeleteAccountHandler")
	}

	if o.AccountDepositToAccountHandler == nil {
		unregistered = append(unregistered, "account.DepositToAccountHandler")
	}

	if o.AccountFindAccountByNameHandler == nil {
		unregistered = append(unregistered, "account.FindAccountByNameHandler")
	}

	if o.AccountGetAccountByIDHandler == nil {
		unregistered = append(unregistered, "account.GetAccountByIDHandler")
	}

	if o.AccountListAccountsHandler == nil {
		unregistered = append(unregistered, "account.ListAccountsHandler")
	}

	if o.AccountTransferBetweenAccountsHandler == nil {
		unregistered = append(unregistered, "account.TransferBetweenAccountsHandler")
	}

	if o.AccountWithdrawAccountHandler == nil {
		unregistered = append(unregistered, "account.WithdrawAccountHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TestrestAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TestrestAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *TestrestAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *TestrestAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TestrestAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the testrest API
func (o *TestrestAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TestrestAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/account"] = account.NewAddAccount(o.context, o.AccountAddAccountHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/account/{accountID}"] = account.NewDeleteAccount(o.context, o.AccountDeleteAccountHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/account/deposit/{accountID}"] = account.NewDepositToAccount(o.context, o.AccountDepositToAccountHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/findByName"] = account.NewFindAccountByName(o.context, o.AccountFindAccountByNameHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/{accountID}"] = account.NewGetAccountByID(o.context, o.AccountGetAccountByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/accounts"] = account.NewListAccounts(o.context, o.AccountListAccountsHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/account/transfer/{accountID}"] = account.NewTransferBetweenAccounts(o.context, o.AccountTransferBetweenAccountsHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/account/withdrawal/{accountID}"] = account.NewWithdrawAccount(o.context, o.AccountWithdrawAccountHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TestrestAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *TestrestAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
