package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Account account
// swagger:model Account
type Account struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// ctime
	Ctime strfmt.DateTime `json:"ctime,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// mtime
	Mtime strfmt.DateTime `json:"mtime,omitempty"`

	// 20 symbols max
	Name string `json:"name,omitempty"`
}

// Validate validates this account
func (m *Account) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
